### ISSUE TITLE
Add credential support for private repos

### ISSUE THREAD

**Issue by euforia** [d3sw/mold#74]
When projects depend on private repos, there needs to be a way for mold to retrieve those repos and as such a way to pass credentials in.

One option is related to #90 :
- Dev to keep Github token/secret in vault
- Jenkins "Build Project" to read from vault and write to a local mold.env file
- (mold config refs to mold.env as env var source)
- #90 to set env variables in the build container based on the mold.env
- the script of dependency collection (in makefile for example) to ref to env var for Github secret

**Comment by pavelvasilenka** [comment]
@shuoyenl Kristina is currently working on this ticket, could you, please, reassign? (see PR above)

**Comment by shuoyenl** [comment]
@pavelvasilenka As described in the scrum today, what Kristina has done is just part of it. We would prefer to keep the secret in vault instead of checking in the public key. There may be no change required to mold (besides what's already covered by #90) This ticket is mainly to verify things (i.e the five bullet points) work together as planed. It is assigned to you because you will be working on #90 and we may use fuac to test the workflow. Thanks.

**Comment by shuoyenl** [comment]
Secrets can now be passed to mold at build time following the steps below:
- Store secrets in Vault
- Jenkins project reads secrets from Vault at build time and generate a mold.env file containing the secrets
- Mold config refs to the mold.env as env_file, i.e. env_file: mold.env
- The secrets are set as env vars in the build container and can be used for accessing private repos
